### ISSUE TITLE
USER STORY Register a new account

### ISSUE THREAD

**Issue by chancandan** [chancandan/portfolio-project-4-Footie365#2]
As a user I can create an account by entering my details so that I can use the site fully.

**Acceptance Criteria**

- [x] 1. User to able to create their account
- [x] 2. Design and UX is crisp

**Tasks**

- [x] Use allauth to implement account registration form
