### ISSUE TITLE
USER STORY Log into account

### ISSUE THREAD

**Issue by chancandan** [chancandan/portfolio-project-4-Footie365#3]
As a user of the site I can use my credentials so that I can successfully log into my account and access the site's features.

**Acceptance Criteria**

- [x] User can log into the website
- [x] UX looks good
**Tasks**

- [x] Use allauth to create a login form that functions
- [x] Style this
