### ISSUE TITLE
USER STORY Account Log Out

### ISSUE THREAD

**Issue by chancandan** [chancandan/portfolio-project-4-Footie365#4]
As a site user I can successfully log out of my account so that my personal information is protected

**Acceptance Criteria**

- [x] User can successfully log out of their own account
- [x] UX is appealing

**Tasks**

- [x] Create an appealing UX design
- [x] Use allauth so the user can log out
