### ISSUE TITLE
USER STORY - ERD diagram

### ISSUE THREAD

**Issue by chancandan** [chancandan/portfolio-project-4-Footie365#7]
As a developer I can understand my database's relationships so that I can design the database.

**Acceptance Criteria**

- [ ] Understood the content of the database and entries
- [ ] understood their relationships to each other

**Tasks**

- [ ] Built a ERD
- [ ] Designed the site's database
